# See https://jr-books.jmpr.io/training/the-config.yml-file.html
# for documentation
version: ~
front: Deploying Models into Production
admin:
  asana_tag:
  duration: 1.5
  price_band:
cores: 1.0
deb_pkgs: ~
python_pkgs: ~
r_pkgs:
  - ggplot2
  - httr
  - jsonlite
  - kknn
  - palmerpenguins
  - pins
  - plumber
  - tidymodels
  - tidyr
  - vetiver
language: r
lintr: true
notes:
  advert: advert
  render: rmarkdown::render
  watermark:
readme: ~
rss: false
related_courses:
  pre_reqs: ~
  suggested:
    - ~
scripts: ~
seed: ~
trainers:
  primary:
    - '@myles-mitchell'
vignettes: false
website:
  materials:
  name:
  publish: false

