# See https://jr-books.jmpr.io/training/the-config.yml-file.html
# for documentation
version: 0.1.0
front: Deploying Models into \\ Production
project_name: 2024-nicd-mlops
admin:
  asana_tag: 'Workshop: Deploying Models into Production'
  duration: 1.5
  price_band: Z
check_pkgtitle: true
cores: 1.0
deb_pkgs: ~
python_pkgs: ~
r_pkgs: jrNicdVetiver
google_chrome: false
language: r
lintr: true
notes:
  advert: advert
  courses: course-dependencies
  render: rmarkdown::render
  watermark:
readme: ~
rss: false
related_courses:
  pre_reqs:
    - ~
  suggested:
    - ~
scripts: ~
seed: ~
trainers:
  primary: '@myles-mitchell'
vignettes: false
website:
  materials:
  name:
  publish: false

